
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-m23/team02-m23-10am-1
owner: ucsb-cs156-m23
repo_name: team02-m23-10am-1
pull_requests: [{"author":{"id":"MDQ6VXNlcjYzOTk0NTY2","is_bot":false,"login":"EthanSun210","name":""},"headRefName":"Ethan-ReviewController","number":47,"title":"Create MenuItemReviewController and MenuItemReviewControllerTests","url":"https://github.com/ucsb-cs156-m23/team02-m23-10am-1/pull/47"},{"author":{"id":"MDQ6VXNlcjYzOTk0NTY2","is_bot":false,"login":"EthanSun210","name":""},"headRefName":"main","number":46,"title":"Create database table for MenuItemReview","url":"https://github.com/ucsb-cs156-m23/team02-m23-10am-1/pull/46"}]
